version: '3'

services:
  backend:
    build: ./server
    ports:
      - 3000:3000
    restart: always
    environment:
      - PORT=3000
    depends_on:
      - frontend

  frontend:
    build: ./client
    ports:
      - 80:80
    restart: always

